name: Transalte
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title:output_ext
collections-dir: _docs
collections:
  docs:
    output: true


defaults:
  - scope:
      path: "assets/img"
    values:
      image: true