name: Transalte
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title:output_ext

collections:
<<<<<<< HEAD
  docs:
    output: true
=======
 - docs
output: true
>>>>>>> c3a7b40abf4d827e1ad92536dfe32425ba4eb9fe
